config/routes.rb
Rails.application.routes.draw do
  root to: "stores#index"
  
  resources :articles
  resources :stores

  mount API::Base => '/services'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :name, :store, presence: true
  belongs_to :store
end

app/models/store.rb
class Store < ActiveRecord::Base
  validates :name, presence: true
  has_many :articles
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    rescue_from :all
    
    format :json
    formatter :json, Grape::Formatter::ActiveModelSerializers
    error_formatter :json, API::ErrorFormatter    

    rescue_from Grape::Exceptions::ValidationErrors do |e|
      error_response(message: { success: false, error_msg: "Bad Request", error_code: 400 }, status: 400)
    end

    rescue_from ActiveRecord::RecordNotFound do |e|
      error_response(message: { success: false, error_msg: "Record Not Found", error_code: 404 }, status: 404)
    end

    before do
      error!({ success: false, error_msg: "Unauthorized", error_code: 401 }, 401) unless authenticated
    end

    helpers do
      def authenticated
        headers['Authorization'] == "Basic bXlfdXNlcjpteV9wYXNzd29yZA=="
      end
    end
   
    mount API::Services::Stores
    mount API::Services::Articles
  end
end

app/controllers/api/error_formatter.rb
module API
  module ErrorFormatter
    def self.call message, backtrace, options, env
      if message.is_a?(Hash)
      	message.to_json
      else
      	{ success: false, error_code: options[:default_status], error_msg: message }.to_json
      end
    end
  end
end

app/controllers/api/services/articles.rb
module API
  module Services
    class Articles < Grape::API
      resource :articles do
        
        desc "Load all the articles that are in the Database."
        get do
          render Article.all, { meta: true, meta_key: :success }
        end
        
        desc "Load all the articles from a specific store that are in the Database."
        params do
          requires :id, type: Integer, desc: "Store id."
        end
        get "stores/:id" do
          render Store.find(params[:id]).articles, { meta: true, meta_key: :success }
        end
      end
    end
  end
end

app/controllers/api/services/stores.rb
module API
  module Services
    class Stores < Grape::API
      resource :stores do
        desc "Load all the stores that are stored in the Database."
        get do
          render Store.all, { meta: true, meta_key: :success }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :description, :price, :total_in_shelf, :total_in_vault, :store_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :total_in_shelf %><br>
    <%= f.text_field :total_in_shelf %>
  </div>
  <div class="field">
    <%= f.label :total_in_vault %><br>
    <%= f.text_field :total_in_vault %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.select :store_id, options_from_collection_for_select(Store.all, :id, :name, @article.store_id) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Total in shelf</th>
      <th>Total in vault</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.description %></td>
        <td><%= article.price %></td>
        <td><%= article.total_in_shelf %></td>
        <td><%= article.total_in_vault %></td>
        <td><%= link_to article.store.name, store_path(article.store) %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @article.price %>
</p>

<p>
  <strong>Total in shelf:</strong>
  <%= @article.total_in_shelf %>
</p>

<p>
  <strong>Total in vault:</strong>
  <%= @article.total_in_vault %>
</p>

<p>
  <strong>Store:</strong>
  <%= link_to @article.store.name, store_path(@article.store) %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Super Shoes" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%= render partial: 'shared/nav_bar' %>
      
      <div class="row">
        <div class="small-12 column">
          <%= yield %>
        </div>
      </div>
    </div>
    
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="small-12 column">
      <p class="copyright">&copy; 2014 Super Shoes</p>
    </div>
  </div>
</footer>

app/views/shared/_nav_bar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Super Shoes</a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Stores", stores_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Articles", articles_path %></li>
    </ul>
  </section>
</nav>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<% unless @store.articles.empty? %>
  <h3>Articles</h3>
  <% @store.articles.each do |article| %>
    <p>
      <strong>Name:</strong>
      <%= link_to article.name, article_path(article) %>
    </p>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>